spring:
  datasource:
    url: jdbc:postgresql://ec2-18-210-64-223.compute-1.amazonaws.com:5432/d3ed4vqeea90f9
    username: kjvkngufyiqehd
    password: 639c3d8f73a7a9aca95013fe879675f03500da624ad644c52791e3f88127e19f
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8081

