server:
  port: 8081
spring:
  application:
    name: ms-usuario
  profiles:
    active: [dev,observability ]
  datasource:
    url: jdbc:postgresql://ec2-18-210-64-223.compute-1.amazonaws.com:5432/d3ed4vqeea90f9
    username: kjvkngufyiqehd
    password: 639c3d8f73a7a9aca95013fe879675f03500da624ad644c52791e3f88127e19f
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update


management:
  metrics:
    tags:
      application: ${spring.application.name}
      service: ${spring.application.name}
      instance: ${spring.application.name}
    enable:
      jvm: true
      process: true
      tomcat: true
      system: true
      logback: true
    distribution:
      slo:
        http.server.requests: 50ms
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.99
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  endpoint:
    metrics:
      enabled: true

